=== qwe522y/billboard05/src/test/resources/unitils/xsd/dataset.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:dflt="billboard_test">
	<xsd:import namespace="billboard_test" schemaLocation="billboard_test.xsd" />
	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="billboard_sides" type="dflt:billboard_sides__type" />
				<xsd:element name="cities" type="dflt:cities__type" />
				<xsd:element name="billboard_types" type="dflt:billboard_types__type" />
				<xsd:element name="billboards" type="dflt:billboards__type" />
				<xsd:element name="timetables" type="dflt:timetables__type" />
				<xsd:element name="dbmaintain_scripts" type="dflt:dbmaintain_scripts__type" />
				<xsd:element name="owners" type="dflt:owners__type" />
				<xsd:element name="billboard_formats" type="dflt:billboard_formats__type" />
				<xsd:element name="agents" type="dflt:agents__type" />
				<xsd:any namespace="billboard_test" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== qwe522y/billboard05/src/test/resources/unitils/BillboardServiceImplTest.xml
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/dataset.xsd">
    <agents id="1" login="barak" name="Барак Обама"/>
    <agents id="2" login="bill" name="Билл Клинтон"/>

    <owners id="3" name="Саб-зиро"/>
    <owners id="4" name="Скорпион"/>

    <cities id="5" name="Москва"/>
    <cities id="6" name="Берлин"/>

    <billboard_types id="7" surface="1"/>
    <billboard_types id="8" surface="2"/>

    <billboards id="96" name="Боль" city="6"  agent_id="1" type="7" owner_id="4" light="true"/>
    <billboards id="97" name="Паника" city="5"  agent_id="1" type="8" owner_id="4" light="true"/>
    <billboards id="98" name="Тревога" city="6"  agent_id="2" type="7" owner_id="3" light="true"/>
    <billboards id="99" name="Страх" city="5"  agent_id="2" type="8"  owner_id="3" light="true"/>
</dataset>

=== qwe522y/billboard05/src/test/resources/unitils/TimetableServiceImplTest.xml
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/dataset.xsd">
    <billboard_sides billboard_id="100" id="1" name="A" rent="100.00"/>

    <timetables id="1001" year="2017" month="0" rent="110.00" side_id="1" surface="0" status="0"/>
    <timetables id="1002" year="2017" month="1" rent="120.00" side_id="1" surface="0" status="1000"/>

    <timetables id="1003" year="2017" month="0" rent="210.00" side_id="1" surface="1" status="0"/>
    <timetables id="1004" year="2017" month="1" rent="220.00" side_id="1" surface="1" status="1000"/>

    <timetables id="1005" year="2017" month="0" rent="310.00" side_id="1" surface="2" status="0"/>
    <timetables id="1006" year="2017" month="1" rent="320.00" side_id="1" surface="2" status="1000"/>
</dataset>

=== qwe522y/billboard05/src/test/resources/unitils/ContractRepositoryJpaImplTest.xml
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/dataset.xsd">
    <billboards id="1" agent_id="999" city_id="1" format_id="1" light="1" owner_id="1" type_id="1"  width="0" height="0"/>
    <billboards id="2" agent_id="999" city_id="1" format_id="1" light="1" owner_id="1" type_id="1"  width="0" height="0"/>
    <billboards id="3" agent_id="1000" city_id="1" format_id="1" light="1" owner_id="1" type_id="1"  width="0" height="0"/>

    <billboard_sides id="98" rent="100.00" surface_count="3" billboard_id="1"/>
    <billboard_sides id="99" rent="100.00" surface_count="3" billboard_id="2"/>
    <billboard_sides id="100" rent="100.00" surface_count="3" billboard_id="3"/>

    <timetables side_id="98" surface="0" year="2017" month="0" rent="100.00" status="0" id="10" />
    <timetables side_id="98" surface="1" year="2017" month="0" rent="100.00" status="0" id="20"/>
    <timetables side_id="98" surface="2" year="2017" month="0" rent="100.00" status="0" id="30"/>
    <timetables side_id="98" surface="0" year="2017" month="0" rent="100.00" status="0" id="40"/>
    <timetables side_id="98" surface="1" year="2017" month="0" rent="100.00" status="0" id="50"/>
    <timetables side_id="98" surface="2" year="2017" month="0" rent="100.00" status="0" id="60"/>

    <timetables side_id="99" surface="0" year="2016" month="11" rent="100.00" status="0" id="70" />
    <timetables side_id="99" surface="1" year="2016" month="11" rent="100.00" status="0" id="80"/>
    <timetables side_id="99" surface="2" year="2016" month="11" rent="100.00" status="0" id="90"/>
    <timetables side_id="99" surface="0" year="2016" month="11" rent="100.00" status="0" id="100"/>
    <timetables side_id="99" surface="1" year="2016" month="11" rent="100.00" status="0" id="110"/>
    <timetables side_id="99" surface="2" year="2016" month="11" rent="100.00" status="0" id="120"/>

    <timetables side_id="100" surface="0" year="2016" month="11" rent="100.00" status="0" id="130" />
    <timetables side_id="100" surface="1" year="2016" month="11" rent="100.00" status="0" id="140"/>
    <timetables side_id="100" surface="2" year="2016" month="11" rent="100.00" status="0" id="150"/>
    <timetables side_id="100" surface="0" year="2016" month="11" rent="100.00" status="0" id="160"/>
    <timetables side_id="100" surface="1" year="2016" month="11" rent="100.00" status="0" id="170"/>
    <timetables side_id="100" surface="2" year="2016" month="11" rent="100.00" status="0" id="180"/>

    <contracts status="0" client_comment="Комментарии клиента1" timetable_id="10"/>
    <contracts status="0" client_comment="Комментарии клиента2" timetable_id="60"/>
    <contracts status="0" client_comment="Комментарии клиента3" timetable_id="70"/>
    <contracts status="0" client_comment="Комментарии клиента4" timetable_id="120"/>
    <contracts status="0" client_comment="Комментарии клиента5" timetable_id="130"/>
</dataset>

=== qwe522y/billboard05/src/test/resources/unitils/ContractServiceTest.xml
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/dataset.xsd">
    <billboards id="1" agent_id="999" city_id="1" format_id="1" light="1" owner_id="1" type_id="1" address="адрес 1"/>
    <billboards id="2" agent_id="999" city_id="1" format_id="1" light="1" owner_id="1" type_id="1" address="адрес 2"/>
    <billboards id="3" agent_id="1000" city_id="1" format_id="1" light="1" owner_id="1" type_id="1" address="адрес 3"/>

    <billboard_sides id="98" rent="100.00" surface_count="3" billboard_id="1" name="имя 1"/>
    <billboard_sides id="99" rent="100.00" surface_count="3" billboard_id="2" name="имя 2"/>
    <billboard_sides id="100" rent="100.00" surface_count="3" billboard_id="3" name="имя 3"/>

    <timetables side_id="98" surface="0" year="2017" month="0" rent="1000.00" status="0" id="10" />
    <timetables side_id="98" surface="1" year="2017" month="0" rent="100.00" status="0" id="20"/>
    <timetables side_id="98" surface="2" year="2017" month="0" rent="100.00" status="0" id="30"/>
    <timetables side_id="98" surface="0" year="2017" month="0" rent="100.00" status="0" id="40"/>
    <timetables side_id="98" surface="1" year="2017" month="0" rent="100.00" status="0" id="50"/>
    <timetables side_id="98" surface="2" year="2017" month="0" rent="2000.00" status="0" id="60"/>

    <timetables side_id="99" surface="0" year="2016" month="11" rent="3000.00" status="0" id="70" />
    <timetables side_id="99" surface="1" year="2016" month="11" rent="100.00" status="0" id="80"/>
    <timetables side_id="99" surface="2" year="2016" month="11" rent="100.00" status="0" id="90"/>
    <timetables side_id="99" surface="0" year="2016" month="11" rent="100.00" status="0" id="100"/>
    <timetables side_id="99" surface="1" year="2016" month="11" rent="100.00" status="0" id="110"/>
    <timetables side_id="99" surface="2" year="2016" month="11" rent="4000.00" status="0" id="120"/>

    <timetables side_id="100" surface="0" year="2016" month="11" rent="100.00" status="0" id="130" />
    <timetables side_id="100" surface="1" year="2016" month="11" rent="100.00" status="0" id="140"/>
    <timetables side_id="100" surface="2" year="2016" month="11" rent="100.00" status="0" id="150"/>
    <timetables side_id="100" surface="0" year="2016" month="11" rent="100.00" status="0" id="160"/>
    <timetables side_id="100" surface="1" year="2016" month="11" rent="100.00" status="0" id="170"/>
    <timetables side_id="100" surface="2" year="2016" month="11" rent="100.00" status="0" id="180"/>

    <contracts status="0" client_comment="Комментарии клиента1" timetable_id="10"/>
    <contracts status="0" client_comment="Комментарии клиента2" timetable_id="60"/>
    <contracts status="0" client_comment="Комментарии клиента3" timetable_id="70"/>
    <contracts status="0" client_comment="Комментарии клиента4" timetable_id="120"/>
    <contracts status="0" client_comment="Комментарии клиента5" timetable_id="130"/>
</dataset>

=== qwe522y/billboard05/src/test/resources/unitils/TimetableRepositoryJpaImplTest.xml
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/dataset.xsd">
    <billboards id="98" city_id="1"  agent_id="1" type_id="2" format_id="2" light="true" rent="100.00" owner_id="1" side_num="2" surface_num_per_side="3" address="Пр. Шамиля 1"/>

    <timetables billboard_id="98" side="0" surface="0" year="2017" month="0" rent="100.00"/>
    <timetables billboard_id="98" side="0" surface="1" year="2017" month="0" rent="100.00"/>
    <timetables billboard_id="98" side="0" surface="2" year="2017" month="0" rent="100.00"/>
    <timetables billboard_id="98" side="1" surface="0" year="2017" month="0" rent="100.00"/>
    <timetables billboard_id="98" side="1" surface="1" year="2017" month="0" rent="100.00"/>
    <timetables billboard_id="98" side="1" surface="2" year="2017" month="0" rent="100.00"/>

    <timetables billboard_id="98" side="0" surface="0" year="2016" month="11" rent="100.00"/>
    <timetables billboard_id="98" side="0" surface="1" year="2016" month="11" rent="100.00"/>
    <timetables billboard_id="98" side="0" surface="2" year="2016" month="11" rent="100.00"/>
    <timetables billboard_id="98" side="1" surface="0" year="2016" month="11" rent="100.00"/>
    <timetables billboard_id="98" side="1" surface="1" year="2016" month="11" rent="100.00"/>
    <timetables billboard_id="98" side="1" surface="2" year="2016" month="11" rent="100.00"/>

    <timetables billboard_id="98" side="0" surface="0" year="2016" month="10" rent="100.00"/>
    <timetables billboard_id="98" side="0" surface="1" year="2016" month="10" rent="100.00"/>
    <timetables billboard_id="98" side="0" surface="2" year="2016" month="10" rent="100.00"/>
    <timetables billboard_id="98" side="1" surface="0" year="2016" month="10" rent="100.00"/>
    <timetables billboard_id="98" side="1" surface="1" year="2016" month="10" rent="100.00"/>
    <timetables billboard_id="98" side="1" surface="2" year="2016" month="10" rent="100.00"/>

    <!-- устаревшие -->
    <timetables billboard_id="98" side="0" surface="0" year="2016" month="9"/>
    <timetables billboard_id="98" side="0" surface="0" year="2015" month="11"/>

    <!-- от других билбордов -->
    <timetables billboard_id="99" side="0" surface="0" year="2017" month="0"/>

</dataset>

=== qwe522y/billboard05/src/test/resources/unitils/ContractControllerTest.xml
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/dataset.xsd">
    <agents id="999" login="testAgent"/>
    <billboards id="1" agent_id="999" city_id="1" format_id="1" light="1" owner_id="1" type_id="1"/>
    <billboard_sides id="98" rent="100.00" surface_count="3" billboard_id="1"/>
    <timetables side_id="98" surface="0" year="2017" month="0" rent="100.00" status="0" id="10" />
    <contracts id="1" status="1" client_comment="Комментарии клиента1" timetable_id="10"/>


    <agents id="9991" login="testAgent"/>
    <billboards id="11" agent_id="999" city_id="1" format_id="1" light="1" owner_id="1" type_id="1"/>
    <billboard_sides id="981" rent="100.00" surface_count="3" billboard_id="1"/>
    <timetables id="100" side_id="98" surface="0" year="2017" month="0" rent="100.00" status="0"  />
</dataset>
